use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));

    // Proto root is 5 levels up from crates/client/ -> crates -> tui -> packages -> client -> root
    let proto_root = manifest_dir
        .join("..")
        .join("..")
        .join("..")
        .join("..")
        .join("..")
        .join("proto");

    let proto_root = proto_root
        .canonicalize()
        .unwrap_or_else(|_| panic!("Proto root not found at {}", proto_root.display()));

    let proto_dir = proto_root.join("meza").join("v1");
    assert!(
        proto_dir.exists(),
        "Proto directory not found at {}",
        proto_dir.display()
    );

    // MVP proto files (chat.proto imports presence.proto, so include it)
    let proto_files: Vec<PathBuf> = [
        "models.proto",
        "auth.proto",
        "chat.proto",
        "gateway.proto",
        "keys.proto",
        "presence.proto",
    ]
    .iter()
    .map(|f| proto_dir.join(f))
    .collect();

    // Verify all proto files exist
    for proto in &proto_files {
        assert!(proto.exists(), "Proto file not found: {}", proto.display());
    }

    let out_dir = manifest_dir.join("src").join("proto");
    std::fs::create_dir_all(&out_dir)?;

    prost_build::Config::new()
        .out_dir(&out_dir)
        .bytes(&[".meza.v1.GatewayEnvelope.payload"])
        .compile_protos(&proto_files, &[&proto_root])?;

    // Generate mod.rs that includes all generated modules
    let mod_content = "// @generated by prost-build - do not edit\n\
                       #![allow(clippy::all)]\n\
                       #![allow(warnings)]\n\
                       include!(\"meza.v1.rs\");\n";
    std::fs::write(out_dir.join("mod.rs"), mod_content)?;

    Ok(())
}
