/**
 * Device-to-device recovery: transfer identity keypair via ECIES.
 *
 * When a user has lost both their password and recovery phrase,
 * a second logged-in device can wrap the identity keypair to an
 * ephemeral X25519 public key generated by the requesting device.
 *
 * Uses the same ECIES pattern as channel key wrapping (primitives.ts)
 * but with a different HKDF info string for domain separation and
 * wrapping 64 bytes (identity keypair) instead of 32 bytes (channel key).
 */

import { x25519 } from '@noble/curves/ed25519.js';
import type { IdentityKeypair } from './primitives.ts';
import {
  deserializeIdentity,
  rejectLowOrderPoint,
  serializeIdentity,
} from './primitives.ts';

const RECOVERY_WRAP_INFO = new TextEncoder().encode('meza-device-recovery-v1');

/**
 * Generate an ephemeral X25519 keypair for the recovery handshake.
 * The requesting device generates this and sends the public key to the server.
 */
export function generateRecoveryKeypair(): {
  publicKey: Uint8Array;
  secretKey: Uint8Array;
} {
  return x25519.keygen();
}

/**
 * Derive a 6-digit verification code from an ephemeral public key.
 * SHA-256(ephemeral_pub) mod 1000000, zero-padded, displayed as "XXX XXX".
 */
export async function deriveVerificationCode(
  ephemeralPub: Uint8Array,
): Promise<string> {
  const hash = await crypto.subtle.digest('SHA-256', ephemeralPub);
  const view = new DataView(hash);
  // Use first 4 bytes as uint32, mod 1000000
  const num = view.getUint32(0) % 1000000;
  const padded = num.toString().padStart(6, '0');
  return `${padded.slice(0, 3)} ${padded.slice(3)}`;
}

/**
 * Wrap an identity keypair for recovery using ECIES.
 *
 * The approving device calls this to wrap its identity keypair
 * to the requesting device's ephemeral X25519 public key.
 *
 * 1. Generate ephemeral X25519 keypair (sender's ephemeral)
 * 2. DH with recipient's ephemeral X25519 public key
 * 3. HKDF-SHA256(shared, salt=sender_ephemeral_pub||recipient_ephemeral_pub, info="meza-device-recovery-v1")
 * 4. AES-256-GCM encrypt the serialized identity (64 bytes)
 *
 * Returns a 124-byte envelope: [sender_ephemeral_pub(32) || nonce(12) || ciphertext(80)]
 * (80 = 64 bytes identity + 16 bytes GCM auth tag)
 */
export async function wrapIdentityForRecovery(
  identity: IdentityKeypair,
  recipientEphemeralPub: Uint8Array,
): Promise<Uint8Array> {
  rejectLowOrderPoint(recipientEphemeralPub, 'recipient ephemeral public key');

  const serialized = serializeIdentity(identity);

  // Sender's ephemeral X25519 keypair
  const senderEphemeral = x25519.keygen();

  // DH shared secret
  const shared = x25519.getSharedSecret(
    senderEphemeral.secretKey,
    recipientEphemeralPub,
  );

  // HKDF salt = sender_ephemeral_pub || recipient_ephemeral_pub
  const salt = new Uint8Array(64);
  salt.set(senderEphemeral.publicKey, 0);
  salt.set(recipientEphemeralPub, 32);

  // Derive wrapping key via HKDF-SHA256
  const hkdfKey = await crypto.subtle.importKey(
    'raw',
    shared as BufferSource,
    'HKDF',
    false,
    ['deriveKey'],
  );
  const wrappingKey = await crypto.subtle.deriveKey(
    { name: 'HKDF', hash: 'SHA-256', salt, info: RECOVERY_WRAP_INFO },
    hkdfKey,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt'],
  );

  // Encrypt serialized identity with AES-256-GCM
  const nonce = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv: nonce },
    wrappingKey,
    serialized as BufferSource,
  );

  // Pack envelope: [sender_ephemeral_pub(32) || nonce(12) || ciphertext(80)]
  const envelope = new Uint8Array(32 + 12 + ciphertext.byteLength);
  envelope.set(senderEphemeral.publicKey, 0);
  envelope.set(nonce, 32);
  envelope.set(new Uint8Array(ciphertext), 44);

  return envelope;
}

/**
 * Unwrap an identity keypair from an ECIES recovery envelope.
 *
 * The requesting device calls this after receiving the wrapped bundle.
 *
 * @param envelope 124-byte ECIES envelope from the approving device
 * @param ephemeralSecret The requesting device's ephemeral X25519 secret key
 */
export async function unwrapIdentityFromRecovery(
  envelope: Uint8Array,
  ephemeralSecret: Uint8Array,
): Promise<IdentityKeypair> {
  if (envelope.length !== 124) {
    throw new Error(
      `Invalid recovery envelope size: expected 124, got ${envelope.length}`,
    );
  }

  // Parse envelope
  const senderEphemeralPub = envelope.slice(0, 32);
  const nonce = envelope.slice(32, 44);
  const ciphertext = envelope.slice(44);

  rejectLowOrderPoint(senderEphemeralPub, 'sender ephemeral public key');

  // Our ephemeral public key (for HKDF salt)
  const myEphemeralPub = x25519.getPublicKey(ephemeralSecret);

  // DH shared secret
  const shared = x25519.getSharedSecret(ephemeralSecret, senderEphemeralPub);

  // HKDF salt = sender_ephemeral_pub || recipient_ephemeral_pub (same as in wrap)
  const salt = new Uint8Array(64);
  salt.set(senderEphemeralPub, 0);
  salt.set(myEphemeralPub, 32);

  // Derive wrapping key via HKDF-SHA256
  const hkdfKey = await crypto.subtle.importKey(
    'raw',
    shared as BufferSource,
    'HKDF',
    false,
    ['deriveKey'],
  );
  const wrappingKey = await crypto.subtle.deriveKey(
    { name: 'HKDF', hash: 'SHA-256', salt, info: RECOVERY_WRAP_INFO },
    hkdfKey,
    { name: 'AES-GCM', length: 256 },
    false,
    ['decrypt'],
  );

  // Decrypt identity
  const plaintext = await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: nonce },
    wrappingKey,
    ciphertext as BufferSource,
  );

  return deserializeIdentity(new Uint8Array(plaintext));
}
