BEGIN;

DROP TABLE IF EXISTS bot_webhooks;
DROP TABLE IF EXISTS bot_tokens;
ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_bot_owner_consistency;
ALTER TABLE users DROP COLUMN IF EXISTS bot_owner_id;
ALTER TABLE users DROP COLUMN IF EXISTS is_bot;

COMMIT;
